export default {
  dependencyTypes: ['prod', 'dev', '!peer', '!local'],
  sortPackages: true,
  semverGroups: [
    {
      label: 'enforce versions to match',
      range: '',
      dependencyTypes: ['prod', 'dev'],
      dependencies: ['**'],
      packages: ['**'],
    },
  ],
  sortAz: [
    'scripts',
    'peerDependencies',
    'dependencies',
    'devDependencies',
    'exports',
    'publishConfig',
  ],
  sortFirst: [
    'name',
    'version',
    'description',
    'type',
    'license',
    'private',
    'author',
    'contributors',
    'homepage',
    'repository',
    'bugs',
    'keywords',
    'packageManager',
    'engineStrict',
    'engines',
    'bin',
    'files',
    'exports',
    'publishConfig',
    'scripts',
    'peerDependencies',
    'dependencies',
    'devDependencies',
    'resolutions',
  ],
} satisfies import('syncpack').RcFile
